language: python

python:
  - "2.6"
  - "2.7"
install:
    - source configure etc/conf
    # extra reqs for testings on Travis
    - pip install coverage coveralls
script:
    - coverage run --source=aboutcode setup.py test
after_success:
    - coveralls